var SHEET_NAME="QC";
var REPORT_SHEET="report";
var SHEET_ID="15zQUvhMK4R9PoOdbtQ10SggtsLzRbZDVzcUF0Czh7ig";
var COL={RECEIVED_DATE:0,INTERNAL_ORDER:1,PO_NO:2,ITEM:3,RECEIVED_QTY:4,ORDERED_QTY:5,CHALLAN_NUMBER:6,CHALLAN_DATE:7,COMMENT:8,RESPONSE_DATE:9,MERGE:10,SUPPLIER:11,ITEM_NAME:12,UNIQUE_ID:13,NR_STATUS:14,NR_COMMENT:15,NR_DATE:16,MAIN_STATUS:17,PASS_QTY:18,PASS_COMMENT:19,PASS_DATE:20,FAIL_QTY:21,FAIL_COMMENT:22,FAIL_DATE:23};
var RCOL={ORDER_NO:0,PO_NUMBER:1,ITEM_CODE:2,STATUS_TEXT:3,SUPPLIER:4,ITEM_NAME:5,CHALLAN_NO:6,RECEIVED_QTY:7,COMMENT:8,ACTION_DATE:9,PASS_QTY:10,RESPONSE_DT:11};
var READ_COLS=24;
function doGet(){return HtmlService.createHtmlOutputFromFile("index").setTitle("QC Pending Review").setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function getPendingItems(){var ss=SpreadsheetApp.openById(SHEET_ID);var sheet=ss.getSheetByName(SHEET_NAME);if(!sheet)return{ok:false,error:"Sheet '"+SHEET_NAME+"' not found"};var lastRow=sheet.getLastRow();if(lastRow<2)return{ok:true,rows:[],passedCount:0};var data=sheet.getRange(2,1,lastRow-1,READ_COLS).getValues();var rows=[];var passedCount=0;data.forEach(function(row,i){var mainStatus=String(row[COL.MAIN_STATUS]||"").trim().toLowerCase();if(mainStatus==="pass")passedCount++;if(mainStatus!=="pending")return;var supplier=String(row[COL.SUPPLIER]||"").trim();var itemName=String(row[COL.ITEM_NAME]||row[COL.ITEM]||"").trim();if(!supplier||!itemName)return;rows.push({rowIndex:i+2,receivedDate:fmtDate(row[COL.RECEIVED_DATE]),internalOrder:row[COL.INTERNAL_ORDER],poNo:row[COL.PO_NO],item:row[COL.ITEM],receivedQty:row[COL.RECEIVED_QTY],orderedQty:row[COL.ORDERED_QTY],challanNumber:row[COL.CHALLAN_NUMBER],challanDate:fmtDate(row[COL.CHALLAN_DATE]),supplier:supplier,itemName:itemName,uniqueId:row[COL.UNIQUE_ID],uniqueKey:String(row[COL.INTERNAL_ORDER]||"")+"|"+String(row[COL.PO_NO]||"")+"|"+String(row[COL.ITEM]||""),receivedQtyV:row[COL.FAIL_QTY],pDate:fmtDate(row[COL.RESPONSE_DATE]||row[COL.RECEIVED_DATE]||"")});});return{ok:true,rows:rows.slice(0,300),passedCount:passedCount};}
function markNotRequired(rowIndices,comment){if(!rowIndices||!rowIndices.length)return{ok:false,error:"No rows selected"};var ss=SpreadsheetApp.openById(SHEET_ID);var sheet=ss.getSheetByName(SHEET_NAME);if(!sheet)return{ok:false,error:"Sheet not found"};var now=fmtNow();var rowsData=getRowsData(sheet,rowIndices);rowIndices.forEach(function(rowIdx){sheet.getRange(rowIdx,COL.NR_STATUS+1).setValue("Not Required");sheet.getRange(rowIdx,COL.NR_COMMENT+1).setValue(comment||"");sheet.getRange(rowIdx,COL.NR_DATE+1).setValue(now);sheet.getRange(rowIdx,COL.MAIN_STATUS+1).setValue("Not Required");sheet.getRange(rowIdx,COL.RESPONSE_DATE+1).setValue(now);});SpreadsheetApp.flush();writeToReport(ss,rowsData,"Not Required","",now,comment||"");return{ok:true,updated:rowIndices.length,timestamp:now};}
function markPass(rowIndices,comment,passDate){if(!rowIndices||!rowIndices.length)return{ok:false,error:"No rows selected"};var ss=SpreadsheetApp.openById(SHEET_ID);var sheet=ss.getSheetByName(SHEET_NAME);if(!sheet)return{ok:false,error:"Sheet not found"};var now=fmtNow();var pDateStr=passDate||fmtDate(new Date());var rowsData=getRowsData(sheet,rowIndices);rowIndices.forEach(function(rowIdx){sheet.getRange(rowIdx,COL.MAIN_STATUS+1).setValue("Pass");sheet.getRange(rowIdx,COL.PASS_COMMENT+1).setValue(comment||"");sheet.getRange(rowIdx,COL.PASS_DATE+1).setValue(now);sheet.getRange(rowIdx,COL.MERGE+1).setValue(pDateStr);sheet.getRange(rowIdx,COL.RESPONSE_DATE+1).setValue(now);});SpreadsheetApp.flush();writeToReport(ss,rowsData,"Pass",pDateStr,now,comment||"");return{ok:true,updated:rowIndices.length,timestamp:now};}
function writeToReport(ss,rowsData,statusText,passQty,responseDateTime,comment){try{var rSheet=ss.getSheetByName(REPORT_SHEET);if(!rSheet){rSheet=ss.insertSheet(REPORT_SHEET);rSheet.getRange(1,1,1,12).setValues([["Order No","PO Number","Item Code","Status","Supplier","Item Name","Challan No","Received Qty","Comment","Action Date","Pass Qty / Date","Response Date & Time"]]);}if(!rowsData.length)return;var start=rSheet.getLastRow()+1;var values=rowsData.map(function(rd){return[rd.internalOrder||"",rd.poNo||"",rd.itemCode||"",statusText,rd.supplier||"",rd.itemName||"",rd.challanNumber||"",rd.receivedQty||"",comment||"",fmtDate(responseDateTime),passQty||"",responseDateTime||""];});rSheet.getRange(start,1,values.length,12).setValues(values);SpreadsheetApp.flush();}catch(e){Logger.log("Report write error: "+e.toString());}}
function getRowsData(sheet,rowIndices){var result=[];rowIndices.forEach(function(rowIdx){try{var row=sheet.getRange(rowIdx,1,1,READ_COLS).getValues()[0];result.push({internalOrder:row[COL.INTERNAL_ORDER],poNo:row[COL.PO_NO],itemCode:row[COL.ITEM],supplier:row[COL.SUPPLIER],itemName:row[COL.ITEM_NAME]||row[COL.ITEM],challanNumber:row[COL.CHALLAN_NUMBER],receivedQty:row[COL.RECEIVED_QTY]});}catch(e){}});return result;}
function fmtDate(val){if(!val)return"";if(val instanceof Date)return Utilities.formatDate(val,Session.getScriptTimeZone(),"dd/MM/yyyy");var str=String(val);if(/^\d{4}-\d{2}-\d{2}/.test(str)){var d=new Date(str);if(!isNaN(d.getTime()))return Utilities.formatDate(d,Session.getScriptTimeZone(),"dd/MM/yyyy");}return str;}
function fmtNow(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone(),"dd/MM/yyyy HH:mm:ss");}
